/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab;

import ConnectionProvider.ConnectionProvider;
import Home.*;
import java.awt.Color;
import javax.swing.JFrame;
import Doctor.doctorLogin_Frame;
import com.mysql.cj.xdevapi.Table;
import com.placeholder.PlaceHolder;
import java.awt.HeadlessException;
import java.awt.Image;
import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Packiyaraj
 */
public class labratory extends javax.swing.JFrame {
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pt=null; 
    String dn,dp;
    String u,p,f,l,h,m,ss,g,d,mm,daaa;
    /**
     * Creates new form labratory
     */
    public labratory() {
        initComponents();setExtendedState(JFrame.MAXIMIZED_BOTH);con=ConnectionProvider.getCon();docDashB();
    }
public void docDashB(){
    try{
            String sql22="select count(id) from result ";
        pt=con.prepareStatement(sql22);
        rs=pt.executeQuery();
        if(rs.next()){
            String countofDoc=rs.getString("count(id)");
            totDoc_Icon.setText(countofDoc);}else {JOptionPane.showMessageDialog(null,"Something is Wrong");}
        }catch(HeadlessException | SQLException e){JOptionPane.showMessageDialog(null, e);}
    try{
            String sql22="select count(Code) from test ";
        pt=con.prepareStatement(sql22);
        rs=pt.executeQuery();
        if(rs.next()){
            String countofDoc=rs.getString("count(Code)");
            totDoc_Icon1.setText(countofDoc);}else {JOptionPane.showMessageDialog(null,"Something is Wrong");}
        }catch(HeadlessException | SQLException e){JOptionPane.showMessageDialog(null, e);}   
     try{
            String sql22="select count(id) from  lab_records";
        pt=con.prepareStatement(sql22);
        rs=pt.executeQuery();
        if(rs.next()){
            String countofDoc=rs.getString("count(id)");
            totDoc_Icon2.setText(countofDoc);}else {JOptionPane.showMessageDialog(null,"Something is Wrong");}
        }catch(HeadlessException | SQLException e) {JOptionPane.showMessageDialog(null, "You Don't have Patients yet");}
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doctorDashBoardHeader = new javax.swing.JPanel();
        hospital = new javax.swing.JLabel();
        hospitalIcon = new javax.swing.JLabel();
        aboutUs_Label = new javax.swing.JLabel();
        contactUs_Label = new javax.swing.JLabel();
        minimize_Label = new javax.swing.JLabel();
        close_Label = new javax.swing.JLabel();
        goBack_Label = new javax.swing.JLabel();
        doctorProfile = new javax.swing.JPanel();
        appionment_Label = new javax.swing.JLabel();
        PatientDoctor_Label = new javax.swing.JLabel();
        dashboardDoctor_Label = new javax.swing.JLabel();
        doctorProfilePic_Panel = new javax.swing.JPanel();
        doctortPic = new javax.swing.JLabel();
        appionment_Label1 = new javax.swing.JLabel();
        appionment_Label2 = new javax.swing.JLabel();
        dasBoardDoctor_Tabbed = new javax.swing.JTabbedPane();
        dashBoardDoctor_Panel = new javax.swing.JPanel();
        appoinmentsForYou_Panel = new javax.swing.JPanel();
        totDOC = new javax.swing.JLabel();
        doc1 = new javax.swing.JLabel();
        totDoc_Icon = new javax.swing.JLabel();
        patientUnderYou_Panel = new javax.swing.JPanel();
        totDOC1 = new javax.swing.JLabel();
        doc2 = new javax.swing.JLabel();
        totDoc_Icon1 = new javax.swing.JLabel();
        yourPatientDischarged_Panel = new javax.swing.JPanel();
        totDOC2 = new javax.swing.JLabel();
        doc3 = new javax.swing.JLabel();
        totDoc_Icon2 = new javax.swing.JLabel();
        patientDoctor_Panel = new javax.swing.JPanel();
        btnadd = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtsid = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        txtsid1 = new javax.swing.JTextField();
        txtsid2 = new javax.swing.JTextField();
        txtsid3 = new javax.swing.JTextField();
        txtsid4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txtsid5 = new javax.swing.JTextField();
        btnsearch1 = new javax.swing.JButton();
        txtsid6 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtsid7 = new javax.swing.JTextField();
        txtsid8 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtsid9 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txtsid10 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        txtsid11 = new javax.swing.JTextField();
        txtsid12 = new javax.swing.JTextField();
        txtsid13 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        yourPatientRecord_Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        yourDischargedPatientRecord = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtsid14 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        txtsid15 = new javax.swing.JTextField();
        txtsid16 = new javax.swing.JTextField();
        txtsid17 = new javax.swing.JTextField();
        txtsid18 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        txtsid19 = new javax.swing.JTextField();
        btnadd1 = new javax.swing.JButton();
        YourAppoinments_Panel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        doctorDashBoardFooter = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        doctorDashBoardHeader.setBackground(new java.awt.Color(0, 0, 204));

        hospital.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        hospital.setForeground(new java.awt.Color(255, 255, 255));
        hospital.setText("HOSPITAL");

        hospitalIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/2.Home/HospitalIcon.png"))); // NOI18N

        aboutUs_Label.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        aboutUs_Label.setForeground(new java.awt.Color(255, 255, 255));
        aboutUs_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/2.Home/AboutUs.png"))); // NOI18N
        aboutUs_Label.setText("About Us");
        aboutUs_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutUs_LabelMouseClicked(evt);
            }
        });

        contactUs_Label.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        contactUs_Label.setForeground(new java.awt.Color(255, 255, 255));
        contactUs_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/2.Home/ContactUs.png"))); // NOI18N
        contactUs_Label.setText("Contact Us");
        contactUs_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactUs_LabelMouseClicked(evt);
            }
        });

        minimize_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/2.Home/MinimizeWindow.png"))); // NOI18N
        minimize_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_LabelMouseClicked(evt);
            }
        });

        close_Label.setBackground(new java.awt.Color(0, 0, 204));
        close_Label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        close_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/2.Home/Close.png"))); // NOI18N
        close_Label.setOpaque(true);
        close_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close_LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close_LabelMouseExited(evt);
            }
        });

        goBack_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/2.Home/Go Back.png"))); // NOI18N
        goBack_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goBack_LabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout doctorDashBoardHeaderLayout = new javax.swing.GroupLayout(doctorDashBoardHeader);
        doctorDashBoardHeader.setLayout(doctorDashBoardHeaderLayout);
        doctorDashBoardHeaderLayout.setHorizontalGroup(
            doctorDashBoardHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctorDashBoardHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(goBack_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hospitalIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(hospital, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(670, 670, 670)
                .addComponent(aboutUs_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(contactUs_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(minimize_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        doctorDashBoardHeaderLayout.setVerticalGroup(
            doctorDashBoardHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hospitalIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, doctorDashBoardHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(hospital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aboutUs_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(contactUs_Label))
            .addGroup(doctorDashBoardHeaderLayout.createSequentialGroup()
                .addGroup(doctorDashBoardHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(minimize_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(close_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, doctorDashBoardHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(goBack_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        doctorProfile.setBackground(new java.awt.Color(0, 0, 255));

        appionment_Label.setBackground(new java.awt.Color(0, 0, 255));
        appionment_Label.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        appionment_Label.setForeground(new java.awt.Color(255, 255, 255));
        appionment_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appionment_Label.setText("Tests Table");
        appionment_Label.setOpaque(true);
        appionment_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appionment_LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                appionment_LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                appionment_LabelMouseExited(evt);
            }
        });

        PatientDoctor_Label.setBackground(new java.awt.Color(0, 0, 255));
        PatientDoctor_Label.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        PatientDoctor_Label.setForeground(new java.awt.Color(255, 255, 255));
        PatientDoctor_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PatientDoctor_Label.setText("Lab Test");
        PatientDoctor_Label.setToolTipText("");
        PatientDoctor_Label.setOpaque(true);
        PatientDoctor_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientDoctor_LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PatientDoctor_LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PatientDoctor_LabelMouseExited(evt);
            }
        });

        dashboardDoctor_Label.setBackground(new java.awt.Color(0, 0, 255));
        dashboardDoctor_Label.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dashboardDoctor_Label.setForeground(new java.awt.Color(255, 255, 255));
        dashboardDoctor_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboardDoctor_Label.setText("     Dashboard");
        dashboardDoctor_Label.setOpaque(true);
        dashboardDoctor_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardDoctor_LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardDoctor_LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardDoctor_LabelMouseExited(evt);
            }
        });

        doctorProfilePic_Panel.setBackground(new java.awt.Color(0, 0, 204));

        doctortPic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doctortPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/Lab/la.png"))); // NOI18N

        javax.swing.GroupLayout doctorProfilePic_PanelLayout = new javax.swing.GroupLayout(doctorProfilePic_Panel);
        doctorProfilePic_Panel.setLayout(doctorProfilePic_PanelLayout);
        doctorProfilePic_PanelLayout.setHorizontalGroup(
            doctorProfilePic_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctorProfilePic_PanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(doctortPic, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        doctorProfilePic_PanelLayout.setVerticalGroup(
            doctorProfilePic_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, doctorProfilePic_PanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(doctortPic, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        appionment_Label1.setBackground(new java.awt.Color(0, 0, 255));
        appionment_Label1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        appionment_Label1.setForeground(new java.awt.Color(255, 255, 255));
        appionment_Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appionment_Label1.setText("Add New Test");
        appionment_Label1.setOpaque(true);
        appionment_Label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appionment_Label1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                appionment_Label1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                appionment_Label1MouseExited(evt);
            }
        });

        appionment_Label2.setBackground(new java.awt.Color(0, 0, 255));
        appionment_Label2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        appionment_Label2.setForeground(new java.awt.Color(255, 255, 255));
        appionment_Label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appionment_Label2.setText("History");
        appionment_Label2.setOpaque(true);
        appionment_Label2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appionment_Label2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                appionment_Label2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                appionment_Label2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout doctorProfileLayout = new javax.swing.GroupLayout(doctorProfile);
        doctorProfile.setLayout(doctorProfileLayout);
        doctorProfileLayout.setHorizontalGroup(
            doctorProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appionment_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PatientDoctor_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
            .addComponent(dashboardDoctor_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(doctorProfilePic_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(appionment_Label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(doctorProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(doctorProfileLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(appionment_Label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        doctorProfileLayout.setVerticalGroup(
            doctorProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, doctorProfileLayout.createSequentialGroup()
                .addComponent(doctorProfilePic_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dashboardDoctor_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PatientDoctor_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appionment_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(appionment_Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(doctorProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, doctorProfileLayout.createSequentialGroup()
                    .addContainerGap(487, Short.MAX_VALUE)
                    .addComponent(appionment_Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(112, 112, 112)))
        );

        dasBoardDoctor_Tabbed.setEnabled(false);
        dasBoardDoctor_Tabbed.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        dashBoardDoctor_Panel.setBackground(new java.awt.Color(255, 255, 255));

        appoinmentsForYou_Panel.setBackground(new java.awt.Color(255, 0, 0));
        appoinmentsForYou_Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.white, java.awt.Color.white));

        totDOC.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        totDOC.setForeground(new java.awt.Color(255, 255, 255));
        totDOC.setText("Result Count");

        doc1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        doc1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/4.Doctor/TotalAppoinment.png"))); // NOI18N

        totDoc_Icon.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        totDoc_Icon.setForeground(new java.awt.Color(255, 255, 255));
        totDoc_Icon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout appoinmentsForYou_PanelLayout = new javax.swing.GroupLayout(appoinmentsForYou_Panel);
        appoinmentsForYou_Panel.setLayout(appoinmentsForYou_PanelLayout);
        appoinmentsForYou_PanelLayout.setHorizontalGroup(
            appoinmentsForYou_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appoinmentsForYou_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totDOC, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(appoinmentsForYou_PanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(doc1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totDoc_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        appoinmentsForYou_PanelLayout.setVerticalGroup(
            appoinmentsForYou_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appoinmentsForYou_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(appoinmentsForYou_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totDoc_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doc1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(totDOC, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        patientUnderYou_Panel.setBackground(new java.awt.Color(153, 153, 0));
        patientUnderYou_Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.black, java.awt.Color.black));

        totDOC1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        totDOC1.setForeground(new java.awt.Color(255, 255, 255));
        totDOC1.setText("Test");

        doc2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        doc2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/4.Doctor/PatientsTotali.png"))); // NOI18N

        totDoc_Icon1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        totDoc_Icon1.setForeground(new java.awt.Color(255, 255, 255));
        totDoc_Icon1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout patientUnderYou_PanelLayout = new javax.swing.GroupLayout(patientUnderYou_Panel);
        patientUnderYou_Panel.setLayout(patientUnderYou_PanelLayout);
        patientUnderYou_PanelLayout.setHorizontalGroup(
            patientUnderYou_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientUnderYou_PanelLayout.createSequentialGroup()
                .addGroup(patientUnderYou_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patientUnderYou_PanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(doc2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totDoc_Icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(patientUnderYou_PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(totDOC1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        patientUnderYou_PanelLayout.setVerticalGroup(
            patientUnderYou_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientUnderYou_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patientUnderYou_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totDoc_Icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doc2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(totDOC1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        yourPatientDischarged_Panel.setBackground(new java.awt.Color(0, 0, 153));
        yourPatientDischarged_Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.black, java.awt.Color.black));

        totDOC2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        totDOC2.setForeground(new java.awt.Color(255, 255, 255));
        totDOC2.setText("Records");

        doc3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        doc3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/4.Doctor/Discharged.png"))); // NOI18N

        totDoc_Icon2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        totDoc_Icon2.setForeground(new java.awt.Color(255, 255, 255));
        totDoc_Icon2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout yourPatientDischarged_PanelLayout = new javax.swing.GroupLayout(yourPatientDischarged_Panel);
        yourPatientDischarged_Panel.setLayout(yourPatientDischarged_PanelLayout);
        yourPatientDischarged_PanelLayout.setHorizontalGroup(
            yourPatientDischarged_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yourPatientDischarged_PanelLayout.createSequentialGroup()
                .addGroup(yourPatientDischarged_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(yourPatientDischarged_PanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(doc3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totDoc_Icon2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(yourPatientDischarged_PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(totDOC2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        yourPatientDischarged_PanelLayout.setVerticalGroup(
            yourPatientDischarged_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yourPatientDischarged_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(yourPatientDischarged_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totDoc_Icon2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doc3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(totDOC2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dashBoardDoctor_PanelLayout = new javax.swing.GroupLayout(dashBoardDoctor_Panel);
        dashBoardDoctor_Panel.setLayout(dashBoardDoctor_PanelLayout);
        dashBoardDoctor_PanelLayout.setHorizontalGroup(
            dashBoardDoctor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashBoardDoctor_PanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(appoinmentsForYou_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(patientUnderYou_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(yourPatientDischarged_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        dashBoardDoctor_PanelLayout.setVerticalGroup(
            dashBoardDoctor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashBoardDoctor_PanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(dashBoardDoctor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(appoinmentsForYou_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(patientUnderYou_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yourPatientDischarged_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(449, Short.MAX_VALUE))
        );

        dasBoardDoctor_Tabbed.addTab("   DashBoard   ", dashBoardDoctor_Panel);

        patientDoctor_Panel.setBackground(new java.awt.Color(255, 255, 255));

        btnadd.setBackground(new java.awt.Color(255, 255, 0));
        btnadd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Patient ID");

        txtsid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnsearch.setBackground(new java.awt.Color(255, 153, 0));
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        txtsid1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtsid2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtsid3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtsid4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("First Name");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Last Name");

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setText("Mobile");

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setText("Gender");

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setText("Test Code");

        txtsid5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnsearch1.setBackground(new java.awt.Color(255, 153, 0));
        btnsearch1.setText("Search");
        btnsearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearch1ActionPerformed(evt);
            }
        });

        txtsid6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel39.setText("Test Name");

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel40.setText("Result");

        txtsid7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtsid7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsid7KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsid7KeyTyped(evt);
            }
        });

        txtsid8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtsid8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsid8ActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel41.setText("Range");

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel42.setText("Units");

        txtsid9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel43.setText("Flag");

        txtsid10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel44.setText("Price");

        txtsid11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtsid12.setEditable(false);
        txtsid12.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        txtsid12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtsid12.setText("-");
        txtsid12.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtsid12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsid12ActionPerformed(evt);
            }
        });

        txtsid13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtsid13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsid13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout patientDoctor_PanelLayout = new javax.swing.GroupLayout(patientDoctor_Panel);
        patientDoctor_Panel.setLayout(patientDoctor_PanelLayout);
        patientDoctor_PanelLayout.setHorizontalGroup(
            patientDoctor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientDoctor_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patientDoctor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patientDoctor_PanelLayout.createSequentialGroup()
                        .addGroup(patientDoctor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientDoctor_PanelLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(patientDoctor_PanelLayout.createSequentialGroup()
                                .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12))
                            .addGroup(patientDoctor_PanelLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE))
                            .addGroup(patientDoctor_PanelLayout.createSequentialGroup()
                                .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(patientDoctor_PanelLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(patientDoctor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(patientDoctor_PanelLayout.createSequentialGroup()
                                .addComponent(txtsid, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnsearch))
                            .addComponent(txtsid4, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsid2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsid3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsid1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(patientDoctor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(patientDoctor_PanelLayout.createSequentialGroup()
                                .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsid5, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnsearch1)
                                .addGap(99, 99, 99))
                            .addGroup(patientDoctor_PanelLayout.createSequentialGroup()
                                .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsid6, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(174, 174, 174))
                            .addGroup(patientDoctor_PanelLayout.createSequentialGroup()
                                .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsid8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtsid12, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsid13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(237, 237, 237))
                            .addGroup(patientDoctor_PanelLayout.createSequentialGroup()
                                .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsid9, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(174, 174, 174))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientDoctor_PanelLayout.createSequentialGroup()
                                .addGroup(patientDoctor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(patientDoctor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtsid11, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsid7, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(patientDoctor_PanelLayout.createSequentialGroup()
                                        .addComponent(txtsid10, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)))
                                .addGap(174, 174, 174))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientDoctor_PanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnadd)
                        .addGap(46, 46, 46))))
        );
        patientDoctor_PanelLayout.setVerticalGroup(
            patientDoctor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientDoctor_PanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(patientDoctor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(patientDoctor_PanelLayout.createSequentialGroup()
                        .addGroup(patientDoctor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsearch)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsid5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsearch1))
                        .addGap(41, 41, 41)
                        .addGroup(patientDoctor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsid1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsid6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(patientDoctor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsid3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsid8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsid12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsid13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(patientDoctor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsid2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsid9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(patientDoctor_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(patientDoctor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsid4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsid7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(patientDoctor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientDoctor_PanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtsid10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(patientDoctor_PanelLayout.createSequentialGroup()
                        .addGroup(patientDoctor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(patientDoctor_PanelLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(patientDoctor_PanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)))
                .addGroup(patientDoctor_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsid11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        dasBoardDoctor_Tabbed.addTab("         Test         ", patientDoctor_Panel);

        yourPatientRecord_Panel.setBackground(new java.awt.Color(255, 255, 255));
        yourPatientRecord_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yourPatientRecord_PanelMouseClicked(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "First Name", "Last Name", "Symptoms", "Diagnosis", "Medicine"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout yourPatientRecord_PanelLayout = new javax.swing.GroupLayout(yourPatientRecord_Panel);
        yourPatientRecord_Panel.setLayout(yourPatientRecord_PanelLayout);
        yourPatientRecord_PanelLayout.setHorizontalGroup(
            yourPatientRecord_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yourPatientRecord_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(yourPatientRecord_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1039, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        yourPatientRecord_PanelLayout.setVerticalGroup(
            yourPatientRecord_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yourPatientRecord_PanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addGap(104, 104, 104))
        );

        dasBoardDoctor_Tabbed.addTab("         Test Table     ", yourPatientRecord_Panel);

        yourDischargedPatientRecord.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add New Test");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtsid14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setText("Test Name");

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel46.setText("Range");

        txtsid15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtsid15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsid15ActionPerformed(evt);
            }
        });

        txtsid16.setEditable(false);
        txtsid16.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        txtsid16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtsid16.setText("-");
        txtsid16.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtsid16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsid16ActionPerformed(evt);
            }
        });

        txtsid17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtsid17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsid17ActionPerformed(evt);
            }
        });

        txtsid18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel47.setText("Units");

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel48.setText("Price");

        txtsid19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnadd1.setBackground(new java.awt.Color(51, 255, 51));
        btnadd1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnadd1.setText("Add");
        btnadd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtsid14, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtsid15, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(txtsid16, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtsid17, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(63, 63, 63))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsid18, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsid19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnadd1)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsid14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsid15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsid16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsid17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsid18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsid19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(btnadd1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout yourDischargedPatientRecordLayout = new javax.swing.GroupLayout(yourDischargedPatientRecord);
        yourDischargedPatientRecord.setLayout(yourDischargedPatientRecordLayout);
        yourDischargedPatientRecordLayout.setHorizontalGroup(
            yourDischargedPatientRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yourDischargedPatientRecordLayout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );
        yourDischargedPatientRecordLayout.setVerticalGroup(
            yourDischargedPatientRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yourDischargedPatientRecordLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        dasBoardDoctor_Tabbed.addTab("       Add New Test    ", yourDischargedPatientRecord);

        YourAppoinments_Panel.setBackground(new java.awt.Color(255, 255, 255));

        jTable4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable4.setRowHeight(25);
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout YourAppoinments_PanelLayout = new javax.swing.GroupLayout(YourAppoinments_Panel);
        YourAppoinments_Panel.setLayout(YourAppoinments_PanelLayout);
        YourAppoinments_PanelLayout.setHorizontalGroup(
            YourAppoinments_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YourAppoinments_PanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1022, Short.MAX_VALUE)
                .addContainerGap())
        );
        YourAppoinments_PanelLayout.setVerticalGroup(
            YourAppoinments_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YourAppoinments_PanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        dasBoardDoctor_Tabbed.addTab("      History     ", YourAppoinments_Panel);

        doctorDashBoardFooter.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout doctorDashBoardFooterLayout = new javax.swing.GroupLayout(doctorDashBoardFooter);
        doctorDashBoardFooter.setLayout(doctorDashBoardFooterLayout);
        doctorDashBoardFooterLayout.setHorizontalGroup(
            doctorDashBoardFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        doctorDashBoardFooterLayout.setVerticalGroup(
            doctorDashBoardFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(doctorProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(dasBoardDoctor_Tabbed, javax.swing.GroupLayout.PREFERRED_SIZE, 1066, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(doctorDashBoardFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(doctorDashBoardHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(doctorDashBoardHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dasBoardDoctor_Tabbed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(doctorDashBoardFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutUs_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutUs_LabelMouseClicked
        // TODO add your handling code here:
        new aboutUs_Frame().setVisible(true);    dispose();
    }//GEN-LAST:event_aboutUs_LabelMouseClicked

    private void contactUs_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactUs_LabelMouseClicked
        // TODO add your handling code here:
        new contactUs_Frame().setVisible(true); dispose();
    }//GEN-LAST:event_contactUs_LabelMouseClicked

    private void minimize_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_LabelMouseClicked
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimize_LabelMouseClicked

    private void close_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_LabelMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_close_LabelMouseClicked

    private void close_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_LabelMouseEntered
        // TODO add your handling code here:
        close_Label.setBackground(new Color(255,102,102));
    }//GEN-LAST:event_close_LabelMouseEntered

    private void close_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_LabelMouseExited
        // TODO add your handling code here:
        close_Label.setBackground(new Color(0,0,204));
    }//GEN-LAST:event_close_LabelMouseExited

    private void goBack_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBack_LabelMouseClicked
        // TODO add your handling code here:
        new doctorLogin_Frame().setVisible(true); dispose();
    }//GEN-LAST:event_goBack_LabelMouseClicked

    private void appionment_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appionment_LabelMouseClicked
        // TODO add your handling code here:
        dasBoardDoctor_Tabbed.setSelectedIndex(2);
        String sql1="select Code,Name,Min,Max,Units,Price from test ";
        try {
            pt=con.prepareStatement(sql1);
             rs=pt.executeQuery();
             jTable1.setModel(DbUtils.resultSetToTableModel(rs));
             
        } catch (SQLException e)  {JOptionPane.showMessageDialog(null, "Connection Failure !");} 
    }//GEN-LAST:event_appionment_LabelMouseClicked

    private void appionment_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appionment_LabelMouseEntered
        // TODO add your handling code here:
        appionment_Label.setBackground(new Color(0,0,204));
    }//GEN-LAST:event_appionment_LabelMouseEntered

    private void appionment_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appionment_LabelMouseExited
        // TODO add your handling code here:
        appionment_Label.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_appionment_LabelMouseExited

    private void PatientDoctor_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientDoctor_LabelMouseClicked
        // TODO add your handling code here:
        dasBoardDoctor_Tabbed.setSelectedIndex(1);
    }//GEN-LAST:event_PatientDoctor_LabelMouseClicked

    private void PatientDoctor_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientDoctor_LabelMouseEntered
        // TODO add your handling code here:
        PatientDoctor_Label.setBackground(new Color(0,0,204));
    }//GEN-LAST:event_PatientDoctor_LabelMouseEntered

    private void PatientDoctor_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientDoctor_LabelMouseExited
        // TODO add your handling code here:
        PatientDoctor_Label.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_PatientDoctor_LabelMouseExited

    private void dashboardDoctor_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardDoctor_LabelMouseClicked
        // TODO add your handling code here:
        dasBoardDoctor_Tabbed.setSelectedIndex(0);
    }//GEN-LAST:event_dashboardDoctor_LabelMouseClicked

    private void dashboardDoctor_LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardDoctor_LabelMouseEntered
        // TODO add your handling code here:
        dashboardDoctor_Label.setBackground(new Color(0,0,204));
    }//GEN-LAST:event_dashboardDoctor_LabelMouseEntered

    private void dashboardDoctor_LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardDoctor_LabelMouseExited
        // TODO add your handling code here:
        dashboardDoctor_Label.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_dashboardDoctor_LabelMouseExited

    private void appionment_Label1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appionment_Label1MouseClicked
        // TODO add your handling code here:
        dasBoardDoctor_Tabbed.setSelectedIndex(3);
    }//GEN-LAST:event_appionment_Label1MouseClicked

    private void appionment_Label1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appionment_Label1MouseEntered
        // TODO add your handling code here:
        appionment_Label1.setBackground(new Color(0,0,204));
    }//GEN-LAST:event_appionment_Label1MouseEntered

    private void appionment_Label1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appionment_Label1MouseExited
        // TODO add your handling code here:
        appionment_Label1.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_appionment_Label1MouseExited

    private void appionment_Label2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appionment_Label2MouseClicked
        // TODO add your handling code here:
        dasBoardDoctor_Tabbed.setSelectedIndex(4);
         String sql1="select patient_id as 'Patient ID',code as 'Code',name as 'Test Name',min as 'Minimium',max as 'Max',results as 'Results',price as 'Price',date as 'Date' from lab_records ";
          try {
            pt=con.prepareStatement(sql1);
             rs=pt.executeQuery();
             jTable4.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {JOptionPane.showMessageDialog(null, "Connection Failure !");}
    }//GEN-LAST:event_appionment_Label2MouseClicked

    private void appionment_Label2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appionment_Label2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_appionment_Label2MouseEntered

    private void appionment_Label2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appionment_Label2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_appionment_Label2MouseExited

    private void yourPatientRecord_PanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yourPatientRecord_PanelMouseClicked
        //        // TODO add your handling code here:
        //        String sql1="select * from appoinment ";
        //        try {
            //            pt=con.prepareStatement(sql1);
            //             rs=pt.executeQuery();
            //             jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            //        } catch (Exception e) {JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_yourPatientRecord_PanelMouseClicked

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        try {
            String sql = "insert into result"
            +"(patient_id,code,name, min, max, units, results,price) "
            + "values (?,?,?,?,?,?,?,?)";
            pt = con.prepareStatement(sql);
            pt.setString(1, txtsid.getText());
            pt.setString(2, txtsid5.getText());
            pt.setString(3, txtsid6.getText());
            pt.setString(4, txtsid8.getText());
            pt.setString(5, txtsid13.getText());
            pt.setString(6, txtsid9.getText());
            pt.setString(7, txtsid7.getText());
            pt.setString(8, txtsid11.getText());
            pt.execute();
            JOptionPane.showMessageDialog(null, "Records added");
                        rs.close();
                        pt.close();
                        txtsid.setText("");txtsid1.setText("");txtsid2.setText("");txtsid3.setText("");txtsid4.setText("");
                        txtsid5.setText("");txtsid6.setText("");txtsid7.setText("");txtsid8.setText("");
                        txtsid9.setText("");txtsid10.setText("");txtsid11.setText("");txtsid13.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        String sql12 = "select P_FirstName,P_LastName,P_Mobile,P_Gender from patient where P_UserName=?";
        try {
            pt = con.prepareStatement(sql12);
            pt.setString(1, txtsid.getText());
            rs = pt.executeQuery();
            if (rs.next()) {
                String add6 = rs.getString(1);
                txtsid1.setText(add6);

                String add7 = rs.getString(2);
                txtsid2.setText(add7);

                String add8 = rs.getString(3);
                txtsid3.setText(add8);

                String add9 = rs.getString(4);
                txtsid4.setText(add9);
                
                

//                String add10 = rs.getString("year");
//                txtyear.setText(add10);
//
//                String add11 = rs.getString("semester");
//                txtsemister.setText(add11);
//
//                String add13 = rs.getString("book_id");
//                txtbid.setText(add13);
//
//                String add1 = rs.getString("b_name");
//                txtbname.setText(add1);
//
//                String add2 = rs.getString("edition");
//                txtedition.setText(add2);
//
//                String add3 = rs.getString("publisher");
//                txtpub.setText(add3);
//
//                String add4 = rs.getString("price");
//                txtprice.setText(add4);
//
//                String add5 = rs.getString("stock");
//                txtstock.setText(add5);
//
//                String add12 = rs.getString("doi");
//                txtdoi.setText(add12);

                rs.close();
                pt.close();
            } else {
                JOptionPane.showMessageDialog(null, "Patient ID not found");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                rs.close();
                pt.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnsearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearch1ActionPerformed
        // TODO add your handling code here:
        String sql12 = "select Name,Min,Max,Units,Price from test where Code=?";
        try {
            pt = con.prepareStatement(sql12);
            pt.setString(1, txtsid5.getText());
            rs = pt.executeQuery();
            if (rs.next()) {
                String add6 = rs.getString(1);
                txtsid6.setText(add6);

                String add7 = rs.getString(2);
                txtsid8.setText(add7);

                String add8 = rs.getString(3);
                txtsid13.setText(add8);

                String add9 = rs.getString(4);
                txtsid9.setText(add9);
                
                String add19 = rs.getString(5);
                txtsid11.setText(add19);
                
                rs.close();
                pt.close();
            } else {
                JOptionPane.showMessageDialog(null, "Code not found");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                rs.close();
                pt.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnsearch1ActionPerformed

    private void txtsid8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsid8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsid8ActionPerformed

    private void txtsid12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsid12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsid12ActionPerformed

    private void txtsid13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsid13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsid13ActionPerformed

    private void txtsid7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsid7KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsid7KeyTyped

    private void txtsid7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsid7KeyReleased
        // TODO add your handling code here:
        
        String mi = txtsid8.getText();String ma = txtsid13.getText();String re = txtsid7.getText();
        int foo1 = Integer.parseInt(mi);int foo2 = Integer.parseInt(ma);int foo3 = Integer.parseInt(re);
        if(foo3<foo1){txtsid10.setText("Low");jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/Lab/Down.gif"))); }
        else if(foo3>foo2){txtsid10.setText("High");jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/Lab/Up.gif"))); }
        else{txtsid10.setText("Nil");jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/Lab/Nil.gif"))); }
    }//GEN-LAST:event_txtsid7KeyReleased

    private void txtsid15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsid15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsid15ActionPerformed

    private void txtsid16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsid16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsid16ActionPerformed

    private void txtsid17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsid17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsid17ActionPerformed

    private void btnadd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd1ActionPerformed
        // TODO add your handling code here:
        try{
        pt=con.prepareStatement("insert into test(Name,Min,Max,Units,Price) values(?,?,?,?,?)"); 
            pt.setString(1,txtsid14.getText() ); 
            pt.setString(2,txtsid15.getText() );
            pt.setString(3,txtsid17.getText() );
            pt.setString(4,txtsid18.getText() );
            pt.setString(5,txtsid19.getText() );
            pt.executeUpdate();}catch(Exception e){System.out.println("Connectio Failure");}
        txtsid14.setText("");txtsid15.setText("");txtsid17.setText("");txtsid18.setText("");txtsid19.setText("");
        JOptionPane.showMessageDialog(null, "Added ");
    }//GEN-LAST:event_btnadd1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(labratory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(labratory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(labratory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(labratory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new labratory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PatientDoctor_Label;
    private javax.swing.JPanel YourAppoinments_Panel;
    private javax.swing.JLabel aboutUs_Label;
    private javax.swing.JLabel appionment_Label;
    private javax.swing.JLabel appionment_Label1;
    private javax.swing.JLabel appionment_Label2;
    private javax.swing.JPanel appoinmentsForYou_Panel;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnadd1;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnsearch1;
    private javax.swing.JLabel close_Label;
    private javax.swing.JLabel contactUs_Label;
    private javax.swing.JTabbedPane dasBoardDoctor_Tabbed;
    private javax.swing.JPanel dashBoardDoctor_Panel;
    private javax.swing.JLabel dashboardDoctor_Label;
    private javax.swing.JLabel doc1;
    private javax.swing.JLabel doc2;
    private javax.swing.JLabel doc3;
    private javax.swing.JPanel doctorDashBoardFooter;
    private javax.swing.JPanel doctorDashBoardHeader;
    private javax.swing.JPanel doctorProfile;
    private javax.swing.JPanel doctorProfilePic_Panel;
    private javax.swing.JLabel doctortPic;
    private javax.swing.JLabel goBack_Label;
    private javax.swing.JLabel hospital;
    private javax.swing.JLabel hospitalIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel minimize_Label;
    private javax.swing.JPanel patientDoctor_Panel;
    private javax.swing.JPanel patientUnderYou_Panel;
    private javax.swing.JLabel totDOC;
    private javax.swing.JLabel totDOC1;
    private javax.swing.JLabel totDOC2;
    private javax.swing.JLabel totDoc_Icon;
    private javax.swing.JLabel totDoc_Icon1;
    private javax.swing.JLabel totDoc_Icon2;
    private javax.swing.JTextField txtsid;
    private javax.swing.JTextField txtsid1;
    private javax.swing.JTextField txtsid10;
    private javax.swing.JTextField txtsid11;
    private javax.swing.JTextField txtsid12;
    private javax.swing.JTextField txtsid13;
    private javax.swing.JTextField txtsid14;
    private javax.swing.JTextField txtsid15;
    private javax.swing.JTextField txtsid16;
    private javax.swing.JTextField txtsid17;
    private javax.swing.JTextField txtsid18;
    private javax.swing.JTextField txtsid19;
    private javax.swing.JTextField txtsid2;
    private javax.swing.JTextField txtsid3;
    private javax.swing.JTextField txtsid4;
    private javax.swing.JTextField txtsid5;
    private javax.swing.JTextField txtsid6;
    private javax.swing.JTextField txtsid7;
    private javax.swing.JTextField txtsid8;
    private javax.swing.JTextField txtsid9;
    private javax.swing.JPanel yourDischargedPatientRecord;
    private javax.swing.JPanel yourPatientDischarged_Panel;
    private javax.swing.JPanel yourPatientRecord_Panel;
    // End of variables declaration//GEN-END:variables
}
